UPDATE       
PRI_VOZ_SPEC_SGTIN
SET                tsd = 2
WHERE        (pvId IN ('3150500'))

UPDATE TTN_SSCC SET ost = 0 ,reserved=0
WHERE TTN_SSCC.sscc IN (
    SELECT DISTINCT TTN_SPEC_SGTIN.sscc
    FROM TTN_SPEC_SGTIN
    INNER JOIN PRI_VOZ_SPEC_SGTIN ON PRI_VOZ_SPEC_SGTIN.sgtin = TTN_SPEC_SGTIN.sgtin
    WHERE PRI_VOZ_SPEC_SGTIN.pvid IN ('3150500')
        AND TTN_SPEC_SGTIN.sscc IS NOT NULL
)

UPDATE TTN_SPEC_SGTIN
SET OST = 0,
reserved=0
FROM TTN_SPEC_SGTIN
WHERE TTN_SPEC_SGTIN.SGTIN IN (
    SELECT PRI_VOZ_SPEC_SGTIN.SGTIN 
    FROM PRI_VOZ_SPEC_SGTIN 
    WHERE PRI_VOZ_SPEC_SGTIN.PVID IN ('3150500')
);